#!/usr/bin/env python3
"""List issue reports with filtering and pagination.

This script retrieves issue reports across all components with support for:
- Filtering by component, type (user/external/internal), and active status
- Pagination with limit and offset
- Issue metadata and timestamps

Issue types:
- user: Reported by authenticated users
- external: Reported by external monitoring systems
- internal: Generated by Nobl9 alerts

Usage:
    python list_issues.py [options]

Options:
    --active: Show only active issues
    --limit N: Maximum number of results (default 50)
    --offset N: Skip first N results for pagination (default 0)
    --component-id UUID: Filter by component ID
    --type TYPES: Filter by type (comma-separated: user,external,internal)

Examples:
    # List all issues
    python list_issues.py

    # List only active issues
    python list_issues.py --active

    # List first 10 issues
    python list_issues.py --limit 10

    # List next 10 issues (pagination)
    python list_issues.py --limit 10 --offset 10

    # List issues for a specific component
    python list_issues.py --component-id abc123

    # List only user-reported issues
    python list_issues.py --type user

    # List user and external issues
    python list_issues.py --type user,external

Environment Variables:
    NOBL9_API_TOKEN: Your Nobl9 API token (required)
    NOBL9_ORG: Your organization ID (required)
"""
import sys
import argparse

from examples.common import get_config, StatusPageClient, pretty_print, APIError


def list_issues(
    client: StatusPageClient,
    active: bool = None,
    limit: int = 50,
    offset: int = 0,
    component_id: str = None,
    issue_type: str = None,
) -> dict:
    """List issue reports.

    Args:
        client: StatusPageClient instance.
        active: Filter by active status.
        limit: Maximum results to return.
        offset: Number of results to skip.
        component_id: Filter by component ID.
        issue_type: Filter by type (comma-separated).

    Returns:
        Issue reports list.
    """
    params = {
        "limit": limit,
        "offset": offset,
    }
    if active is not None:
        params["active"] = str(active).lower()
    if component_id:
        params["componentId"] = component_id
    if issue_type:
        params["type"] = issue_type

    return client.get("/status-page/issues", params=params)


def print_issues_summary(items: list) -> None:
    """Print issues in a summary format.

    Args:
        items: List of issue reports.
    """
    if not items:
        print("No issues found.")
        return

    print(f"\nTotal issues: {len(items)}")
    print("\nIssue Reports:")
    print("-" * 80)

    for issue in items:
        type_emoji = {
            "user": "👤",
            "external": "🔌",
            "internal": "⚙️",
        }.get(issue.get("type", ""), "❓")

        print(f"\n{type_emoji} Issue ID: {issue.get('id')}")
        print(f"   Component ID: {issue.get('componentId')}")
        print(f"   Type: {issue.get('type')}")
        print(f"   Occurred at: {issue.get('occurredAt')}")
        print(f"   Reported by: {issue.get('reportedBy')}")

        if issue.get("comment"):
            print(f"   Comment: {issue.get('comment')}")


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description="List issue reports with filtering and pagination"
    )
    parser.add_argument("--active", action="store_true", help="Show only active issues")
    parser.add_argument("--limit", type=int, default=50, help="Maximum results (default 50)")
    parser.add_argument("--offset", type=int, default=0, help="Skip first N results (default 0)")
    parser.add_argument("--component-id", help="Filter by component ID")
    parser.add_argument(
        "--type",
        help="Filter by type (comma-separated: user,external,internal)",
    )

    args = parser.parse_args()

    try:
        config = get_config()
        client = StatusPageClient(config)

        print("Fetching issue reports...")
        result = list_issues(
            client,
            active=args.active if args.active else None,
            limit=args.limit,
            offset=args.offset,
            component_id=args.component_id,
            issue_type=args.type,
        )

        # Print summary
        items = result.get("items", [])
        print_issues_summary(items)

        # Show pagination info
        if result.get("moreDataAvailable"):
            print(f"\n⚠️  More data available. Use --offset {args.offset + args.limit} to see next page.")

        # Print full JSON
        print("\n\nFull Issue Details:")
        print("=" * 80)
        pretty_print(result)

    except APIError as e:
        print(f"API Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Configuration Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
